Funds
-----

Funds should be created for every budget you wish to track. For some libraries this may be a fund per individual collection. Other libraries may only use one fund for all purchasing. Libraries may want to create funds specifically for non-bibliographic purchases, such as processing supplies, or for other charges such as charges for MARC records.

Multi-branch libraries may have a single set of funds for their entire system, a set of funds for each branch, or may use a combination of funds at the branch and system levels.

Create a Fund
~~~~~~~~~~~~~

. Click *Administration* -> *Acquisitions Administration* -> *Funds*
. Click New Fund.
. Enter a Name for the fund. There is no limit to the number of characters that can be entered in this field.
. Create a unique Code for the fund. There is no limit to the number of characters that can be entered in this field.
. Please add your library short code to the end of all fund codes. Example AF_ZSP
. Enter a year for the fund. This can be a fiscal year or a calendar year. The format of the year is YYYY.
. Select an org unit from the drop down menu. The org unit indicates the organizational unit(s) whose staff can use this fund.
.. In a multi-branch system funds may be set to the top organizational unit, the organizational units for branches, or a combination.
. Select a Currency Type from the drop down menu. When a fund is applied to a line item or copy the price of the item will be encumbered in the currency associated with the fund.
. Check the Active box to activate this fund. You cannot make purchases from an inactive fund.
. Enter a Balance Stop Percent. The balance stop percent prevents you from making purchases when only a specified amount of the fund remains. For example, if you want the fund to stop purchases after 95% of the fund has been spent, then you would enter 95 in the field. When the fund reaches its Balance Stop Percent, it will appear in red when you apply funds to copies.
.. If this field is left blank it is possible to overspend the fund.
. The Balance Stop Percent can be adjusted as needed throughout your fiscal year.
. Enter a Balance Warning Percent. The balance warning percent gives you a warning that the fund is low. You can specify any percent. For example, if you want to be warned when 90% of the fund has been spent, then you would enter 90 in the field. When the fund reaches its Balance Warning Percent, it will appear in yellow when you apply funds to copies.
. The Balance Warning Percent can be adjusted as needed throughout your fiscal year.
. Check the Propagate box to propagate funds. When you propagate a fund, Evergreen will create a new fund for the following fiscal year with the same parameters as your current fund. All of the settings transfer except for the year and the amount of money in the fund. Propagation occurs during the fiscal year close-out operation.
. Check the Rollover box if you would like to roll over remaining funds and/or encumbrances during the fiscal year close-out operation into the same fund for the next year.
. Click Save.
. Click Reload.


Edit a Fund
~~~~~~~~~~~

While you are able to edit your fund's name, owner, and code you are unable to edit the balance of your fund. A fund's balance can be adjusted by allocating monies to the fund or transferring monies to another fund.

. Select *Administration* -> *Acquisitions Administration* -> *Funds*.
. Double-click on the row you would like to edit. A pop-up box will appear in which you can edit the fields.
. Make your changes and click *Save*.

NOTE: Do Not edit the currency of an active in-use fund.


Delete a Fund
~~~~~~~~~~~~~

It is possible to delete a fund by checking the box of the fund you wish to delete and clicking Delete Selected.

A Fund can only be deleted if no credit has been applied to it.

Allocate to Funds - Funds Interface
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

anchor:allocate-funds[Allocate to Fund - Funds Interface]

To allocate credits using the Fund Interface:

. Select *Administration* -> *Acquisitions Administration* -> *Funds*.
. Click the hyper linked name of the fund. The Fund Details screen will appear.
. Click *Create Allocation*.
. Choose the Funding Source from the drop down menu.
. Enter the amount you would like to apply to the fund from the funding source.
. Enter a note. (Optional).
. Click *Apply*.

Transfer Credit Between Funds
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The credits that you allocate to funds can be transferred between funds if desired. The system tracks these transfers.

. Select *Administration* -> *Acquisitions Administration* -> *Funds*.
. Click the hyper linked name of the fund. The Fund Details screen will appear.
. Click *Transfer Money*.
. Enter the amount you would like to transfer.
. From the drop down menu, select the code of the destination fund.
. Enter a note. (Optional).
. Click *Transfer*.
. Click *OK* to the pop that appears to confirm that you are ready to commit the transfer.

Track Balances and Expenditures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Fund Details screen allows you to track a fund's balance, encumbrances, and amount spent.

. Select *Administration* -> *Acquisitions Administration* -> *Funds*.
. Click the hyper linked name of the fund. The Fund Details screen will appear.

* *Summary* - The summary tab allows you to track the following:
** _Balance_ - The balance is calculated by subtracting both spent and encumbered funds from the total allocated to the fund.
**  _Total Allocated_ - This amount is the total monies allocated from the Funding Source(s).
**  _Spent Balance_ - This balance is calculated by subtracting only the funds that been invoiced, and so spent, from the total allocated to the fund. It does not included encumbrances.
**  _Total Debits_ - The total debits are calculated by adding together the total spent and total encumbered.
** _Total Spent_ - The total spent is calculated by adding the cost of all items that have been invoiced. It does not include encumbrances.
**  _Total Encumbered_ - The total encumbered is calculated by adding all the encumbrances. It does not include items that have been invoiced.
* *Allocations* - The Allocations tab allows you to track credit allocated from funding sources, transfers to other funds, and transfers from other funds.
* *Debits* - The Debits tab allows you to track all purchases made and monies encumbered against the fund.
* *Tags* - The *Tags* tab allows you to add and delete fund tags. See Fund Tags for more information.

Fund Tags
~~~~~~~~~

Create a Fund Tag
^^^^^^^^^^^^^^^^^

. Select *Administration* -> *Acquisitions Administration* -> *Fund Tags*.
. Click *New Fund Tag*
. Select a the library or branch the fund tag will be used by as the Fund Tag Owner from the drop down menu.
. Enter a Fund Tag Name
. Click Save

Add a Fund Tag to a Fund
^^^^^^^^^^^^^^^^^^^^^^^^

. Select *Administration* -> *Acquisitions Administration* -> *Funds*.
. Click the hyperlinked name of fund you would like to add a tag to. The Fund Details screen will appear.
. Click on the *Tags* tab.
. Click *Add Tag*.
. Select the tag from the drop down menu and click *Add*.

Note: Tags can be removed from funds by clicking the blue X beside the tag.

