Selection Lists
---------------

Selection lists allow you to create, manage, and save lists of items that you may want to purchase. To view your selection list, click
*Acquisitions* -> *My Selection Lists*. Use the general search to view selection lists created by other users.

Create a Selection List
~~~~~~~~~~~~~~~~~~~~~~~

Selection lists can be created in four areas within the module. Selection lists can be created when you <<_brief_records,Add Brief Records>>, Upload MARC Order Records, or find records through the <<_marc_federated_search,MARC Federated Search>>. In each of these interfaces, you will find the Add to Selection List field. Enter the name of the selection list that you want to create in that field.

Selection lists can also be created through the My Selection Lists interface:

.Create a Selection List
. Click *Acquisitions* -> *My Selection Lists*.
. Click the New Selection List drop down arrow.
. Enter the name of the selection list in the box that appears.
. Click Create.

Add items to a selection list
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can add items to a selection list in one of three ways: <<_brief_records,add a brief record>>; upload MARC order records; add records through a <<_marc_federated_search,federated search>>; or use the View/Place Orders menu item in the catalog.

Clone selection lists
^^^^^^^^^^^^^^^^^^^^^

Cloning selection lists enables you to copy one selection list into a new selection list. You can maintain both copies of the list, or you can delete the previous list.

.Clone Selection List
. Click *Acquisitions* -> *My Selection Lists*.
. Check the box adjacent to the list that you want to clone.
. Click Clone Selected.
. Enter a name into the box that appears, and click Clone.


Merge selection lists
^^^^^^^^^^^^^^^^^^^^^

.Merge two or more selection lists into one selection list.
. Click *Acquisitions* -> *My Selection Lists*.
. Check the boxes adjacent to the selection lists that you want to merge, and click Merge Selected.
. Choose the Lead Selection List from the drop down menu. This is the list to which the items on the other list(s) will be transferred.
. Click Merge.

Delete selection lists
^^^^^^^^^^^^^^^^^^^^^^

.Delete selection lists
. Click *Acquisitions* -> *My Selection Lists*.
. Check the box adjacent to the selection list(s) that you want to delete.
. Click Delete Selected.

NOTE: You must delete all line items from a selection list before you can delete the list.

Mark Ready for Selector
^^^^^^^^^^^^^^^^^^^^^^^

After an item has been added to a selection list or purchase order, you can mark it ready for selector. This step is optional but may be useful to individual workflows.

. If you want to mark part of a selection list ready for selector, then you can check the box(es) of the line item(s) that you wish to mark ready for selector. If you want to mark the entire list ready for selector, then skip to step 2.
. Click *Actions* -> *Mark Ready for Selector*.
. A pop up box will appear. Choose to mark the selected line items or all line items.
. Click Go.
. The screen will refresh. The marked line item(s) will be highlighted pink, and the status changes to selector-ready.


Convert selection list to purchase order
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.Convert a selection list to a purchase order.
. From a selection list, click *Actions* -> *Create Purchase Order*.
. A pop up box will appear.
. Select the ordering agency from the drop down menu.
. Enter the provider.
. Check the box adjacent to prepayment required if prepayment is required.
. Choose if you will add All Line items or Selected Line items to your purchase order.
. Check the box if you want to Import Bibs and Create Copies in the catalog.
. Click Submit.
