Working with  Selection Lists
-----------------------------
(((selection lists)))
(((selection lists, create)))
(((selection lists, clone)))
(((selection lists, convert to purchase order)))
(((selection lists, delete)))

Selection lists allow you to create, manage, and save lists of items that you may want to purchase.

For creating selection lists see xref:_creating_selection_lists[].

For adding line items to selection lists see xref:_adding_line_items_to_selection_lists[].

Viewing Selection Lists
~~~~~~~~~~~~~~~~~~~~~~~

.View your Selection Lists
. Click *Acquisitions* -> *My Selection Lists*.
.. Use the general search to view selection lists created by other users.
.. Refer to xref:_search_for_selection_lists[] for details.

Cloning Selection Lists
~~~~~~~~~~~~~~~~~~~~~~~

.Clone Selection List
. Click *Acquisitions* -> *My Selection Lists*.
. Check the box adjacent to the list that you want to clone.
. Click *Clone Selected*.
. Enter a name into the box that appears.
. Click *Clone*.

NOTE: Cloning selection lists enables you to copy one selection list into a 
new selection list. You can maintain both copies of the list, or you can delete the previous list.

Merging Selection Lists
~~~~~~~~~~~~~~~~~~~~~~~

.Merge two or more selection lists into one selection list.
. Click *Acquisitions* -> *My Selection Lists*.
. Check the boxes adjacent to the selection lists that you want to merge, and click *Merge Selected*.
. Choose the Lead Selection List from the drop down menu.
.. This is the list to which the items on the other list(s) will be transferred.
. Click *Merge*.

Deleting Selection Lists
~~~~~~~~~~~~~~~~~~~~~~~~

.Delete Selection List
. Click *Acquisitions* -> *My Selection Lists*.
. Check the box adjacent to the selection list(s) that you want to delete.
. Click *Delete Selected*.

NOTE: You must delete all line items from a selection list before you can delete the list.
