Invoice Item Types
------------------

Invoice Item Types allow you to enter additional charges on a purchase order or invoice.

Charges for bibliographic items are listed separately from these additional charges on a purchase order or invoice.

Invoice Item Types are either set to Prorate = TRUE or Prorate = FALSE. When the *Prorate* button is selected 
on an invoice, the system will prorate any charges where Prorate = TRUE. This means that payment for 
the Invoice Item Type will be divided by all the funds in use on the invoice in proportion to the 
amount being spent by each fund on the invoice.

.Sitka's Invoice Item Type Defaults

* Access Fee (f)
* Blanket Order (f)
* Cataloguing Charge (f)
* Direct Purchase (f)
* GST (No Prorate) (f)
* Goods and Services Tax (t)
* Handling Charge (t)
* Harmonized Sales Tax (t)
* Import Fee (t)
* Lamination fee (t)
* Lamination fee - No Prorate (f)
* Misc - No Prorate (f)
* Non-library Item (f)
* PST (No Prorate) (f)
* Processing Fee - No Prorate (f)
* Processing Fee - Prorate (t)
* Provincial Sales Tax (t)
* Refund (f)
* Serial Subscription (f)
* Serial Supplemental Charges (f)
* Shipping Charge (t)
* Tax (t)

NOTE: A *(t)* indicates that the charge is proratable, a *(f)* indicates that it is not.
